POST http://localhost:5500/ingest HTTP/1.1
content-type: application/json

{
    "fakeUID": "sample",
    "type":"testType",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "dsid": "8b497500-b606-416b-a9fb-a496808efbad",
    "data": [121.0,114.5]
}


##########

POST http://localhost:5500/create HTTP/1.1
content-type: application/json

{
    "fakeUID": "sample",
    "type":"testType"
}